# Generated by Django 4.1.3 on 2023-01-23 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='img_id',
            field=models.IntegerField(default=-1),
        ),
    ]
