# Generated by Django 4.1.3 on 2023-01-23 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_shop', '0002_product_img_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category1',
            field=models.CharField(default='product', max_length=90),
        ),
        migrations.AddField(
            model_name='product',
            name='category2',
            field=models.CharField(default='product', max_length=90),
        ),
        migrations.AddField(
            model_name='product',
            name='category3',
            field=models.CharField(default='product', max_length=90),
        ),
        migrations.AddField(
            model_name='product',
            name='primary_img',
            field=models.ImageField(default='', upload_to='app_shop/images'),
        ),
        migrations.AlterField(
            model_name='product',
            name='images',
            field=models.FileField(default='', upload_to='app_shop/images'),
        ),
    ]
