# Generated by Django 4.1.3 on 2023-02-02 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_shop', '0004_alter_product_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='images',
            field=models.CharField(max_length=1000, default=''),
        ),
    ]
