# Generated by Django 4.1.3 on 2023-02-02 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_shop', '0005_alter_product_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='images',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
