# Generated by Django 4.1.3 on 2023-03-14 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_shop', '0009_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='comments',
            field=models.JSONField(default=''),
        ),
    ]
