# Generated by Django 4.1.3 on 2023-03-14 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_shop', '0010_product_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='comments',
            field=models.JSONField(null=True),
        ),
    ]
