# Generated by Django 4.1.3 on 2023-03-14 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_shop', '0011_alter_product_comments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='comments',
        ),
    ]
