# Generated by Django 4.1.3 on 2023-03-15 09:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_shop', '0013_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('image_id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='app_shop/images')),
                ('price', models.IntegerField(default=0)),
                ('color', models.CharField(default='', max_length=50)),
                ('image_of', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='app_shop.product')),
            ],
        ),
        migrations.DeleteModel(
            name='ProductImages',
        ),
    ]
